# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9568b917669402decdb0a9edf20a1fc9"
name = "Local - HubOn Local Pickup"
handle = "hubon-app"
application_url = "https://efd6-182-253-51-229.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "hubondemodev2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_locations,read_orders,read_product_listings,read_products,read_themes,write_metaobject_definitions,write_metaobjects,write_orders,write_products,write_publications"

[auth]
redirect_urls = [
  "https://efd6-182-253-51-229.ngrok-free.app/auth/callback",
  "https://efd6-182-253-51-229.ngrok-free.app/auth/shopify/callback",
  "https://efd6-182-253-51-229.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
