# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "02001323f3513d1a9b5d44bc071c0f49"
name = "Stag - HubOn Local Pickup"
handle = "hubon-1"
application_url = "https://staging-localpickup.letshubon.com/"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "hubondemostag1.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_product_listings,read_products,read_themes,write_metaobject_definitions,write_metaobjects,write_orders,write_products"

[auth]
redirect_urls = [
  "https://staging-localpickup.letshubon.com/auth/callback",
  "https://staging-localpickup.letshubon.com/auth/shopify/callback",
  "https://staging-localpickup.letshubon.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[pos]
embedded = false
